[package]
name = "sprengui"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR BSL-1.0 OR MIT"
documentation = "https://docs.rs/sprengui"
homepage = "https://github.com/ardaku/sprengui/blob/v0/CHANGELOG.md"
repository = "https://github.com/ardaku/sprengui"
readme = "README.md"
description = "Native-ish GUI Toolkit"
keywords = []
categories = []
rust-version = "1.85.0"

[dependencies.footile]
version = "0.7.0"

[dependencies.hatmil]
version = "0.4.0"

[dependencies.human]
version = "0.2.0"

[dependencies.mundy]
version = "0.1.10"
default-features = false

[dependencies.pasts]
version = "0.11.0" # "0.14.3"

[dependencies.pix]
version = "0.14.0"

[dependencies.whoami]
version = "1.6.0"
